info:
  app:
    version: 1.0
server:
  port: 8081
spring:
  datasource:
    driverClassName: org.h2.Driver
    hikari:
      auto-commit: false
      pool-name: Hikari
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:newjava;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: newjava
    password: ''
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/h2
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
cors:
  allowed:
    origins: '*'

logging:
  level:
    com.senacor.intermission.newjava: DEBUG

management:
  endpoints:
    web:
      exposure:
        exclude: ''
        include: '*'

